services:
  zoo-land-frontend:
    build:
      context: ./zoo-land-frontend
    volumes:
      - ./zoo-land-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - backend

  zoo-land-backend:
    build:
      context: ./zoo-land-backend
    volumes:
      - ./zoo-land-backend:/app
      - /app/node_modules
    ports:
      - "1337:1337"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: zoo_land
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zoo_land
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
